name: ci

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: hongyu97
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx (Cloud builder)
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "hongyu97/stay-tuned"
          install: true

      - name: Build & push image via Build Cloud
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "hongyu97/stay-tuned:latest"
          outputs: type=registry
